[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_TELEMETRY_DISABLED = "1"
  MONGODB_URI = "mongodb+srv://onsitepcn:Nf4Yd5d6zOGDR5zG@cluster2.nr0dy.mongodb.net/onsite?retryWrites=true&w=majority&appName=Cluster2"
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyCjVKYDelG6ASUS6EfYUtOnvJBYhMCA1Lo"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "manusawv.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "manusawv"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "manusawv.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "49788426717"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:49788426717:web:ef1d243368f20cb8363e34"
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-MKGBXDJZFT"
  NEXTAUTH_URL = "https://finalawv.netlify.app"
  NEXTAUTH_SECRET = "your-nextauth-secret-key-here"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Specifically handle NextAuth routes
[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200
  force = true

# Handle other API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Support client-side routing for Next.js App Router - fallback for /*
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Add headers for security and CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Function configuration
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongoose"]

[functions.api]
  timeout = 30
  memory = 2048
  node_bundler = "esbuild"
  external_node_modules = ["mongoose"]
  included_files = ["src/lib/mongodb.ts"]
  runtime = "nodejs18.x"
  maxDuration = 30

# Dedicated auth function configuration
[functions.auth]
  timeout = 30
  memory = 2048
  node_bundler = "esbuild"
  external_node_modules = ["mongoose", "next-auth", "bcryptjs"]
  included_files = ["src/lib/mongodb.ts", "src/lib/auth.ts", "src/models/User.ts"]
  runtime = "nodejs18.x"
  maxDuration = 30 