[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  MONGODB_URI = "mongodb+srv://onsitepcn:8Pkn4n0rUeT25VsQ@cluster1.cv9ak.mongodb.net/annual-wellness-visit"
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyCjVKYDelG6ASUS6EfYUtOnvJBYhMCA1Lo"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "manusawv.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "manusawv"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "manusawv.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "49788426717"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:49788426717:web:ef1d243368f20cb8363e34"
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-MKGBXDJZFT"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add API redirects to avoid CORS issues
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 